In [1]:
import math 
import numpy as np
import pandas as pd 
from scipy.linalg import schur, eigvals

# 12.2.1

In [2]:
def shiftedqr(a):
    tol = 1.e-14
    kounttol = 500L
    m = a.shape[0]
    n = m-1
    lam = np.zeros((m,1), dtype=complex)
    
    while n>0:
        kount = 0
        while max(abs(a[n,0:n])) > tol and kount < kounttol:
            kount = kount+1     # keep track of number of qr’s
            mu = a[n,n]         # shift is mu
            q,r = np.linalg.qr( a - mu*np.eye(n+1))
            a= np.dot(r, q) + mu*np.eye(n+1)
    
        if kount < kounttol:  
            lam[n]=a[n,n] 
            n -= 1
            a = a[:n+1,:n+1] 

        else: #have isolated 2x2 block
            disc = complex(( a[-2,-2] - a[-1,-1] )**2 + 4*a[-1,-2]*a[-2,-1])
            lam[n]=( a[-2,-2] + a[-1,-1] + np.sqrt(disc))/2
            lam[n-1]=( a[-2,-2] + a[-1,-1] - np.sqrt(disc))/2
            n -= 2
            a = a[:n+1,:n+1] 
            
    if n==0: 
        lam[0] = a[0,0] # only a 1x1 block remains
    return lam

In [3]:
def ShurEvalues(A):
    T, Z = schur(A)
    SchurEvalues = T.diagonal()
    Evalues = shiftedqr(A)
     
    print('The Original Matrix is:\n\n',A,'\n')
    print('Upper Triangular Form of Schur Decomposition is:\n\n', T,'\n')
    print('The Unitary Matrix Form of Schur Decomposition is:\n\n',Z, '\n')
    print('The Python Numpy Schur Decomposition Eigenvalues are:\n\n', SchurEvalues, '\n')
    print('The Shifted QR Algorithm Eigenvalues are:\n\n', Evalues, '\n')
    return  

In [4]:
A = np.array([[-3, 3, 5], [1, -5, -5], [6, 6, 4]])
ShurEvalues(A)

The Original Matrix is:

 [[-3  3  5]
 [ 1 -5 -5]
 [ 6  6  4]] 

Upper Triangular Form of Schur Decomposition is:

 [[ 4.         -7.07106781  8.08290377]
 [ 0.         -6.         -3.26598632]
 [ 0.          0.         -2.        ]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[-4.08248290e-01 -5.77350269e-01 -7.07106781e-01]
 [ 4.08248290e-01  5.77350269e-01 -7.07106781e-01]
 [-8.16496581e-01  5.77350269e-01 -2.11265980e-16]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [ 4. -6. -2.] 

The Shifted QR Algorithm Eigenvalues are:

 [[-6.+0.j]
 [-2.+0.j]
 [ 4.+0.j]] 



In [5]:
B = np.array([[3, 1, 2], [1, 3, -2], [2, 2, 6]])
ShurEvalues(B)

The Original Matrix is:

 [[ 3  1  2]
 [ 1  3 -2]
 [ 2  2  6]] 

Upper Triangular Form of Schur Decomposition is:

 [[ 2.00000000e+00 -2.82842712e+00  3.04522188e-15]
 [ 0.00000000e+00  6.00000000e+00  2.82842712e+00]
 [ 0.00000000e+00  0.00000000e+00  4.00000000e+00]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 7.07106781e-01 -6.64778378e-16 -7.07106781e-01]
 [-7.07106781e-01 -3.92630972e-16 -7.07106781e-01]
 [ 7.86274655e-17 -1.00000000e+00  8.60040359e-16]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [2. 6. 4.] 

The Shifted QR Algorithm Eigenvalues are:

 [[2.+0.j]
 [4.+0.j]
 [6.+0.j]] 



In [6]:
C = np.array([[17, 1, 2], [1, 17, -2], [2, 2, 20]])
ShurEvalues(C)

The Original Matrix is:

 [[17  1  2]
 [ 1 17 -2]
 [ 2  2 20]] 

Upper Triangular Form of Schur Decomposition is:

 [[ 1.60000000e+01 -2.82842712e+00  1.71675698e-15]
 [ 0.00000000e+00  2.00000000e+01  2.82842712e+00]
 [ 0.00000000e+00  0.00000000e+00  1.80000000e+01]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 7.07106781e-01  4.06690548e-17 -7.07106781e-01]
 [-7.07106781e-01 -9.38886511e-16 -7.07106781e-01]
 [ 8.32447327e-16 -1.00000000e+00  6.84940685e-16]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [16. 20. 18.] 

The Shifted QR Algorithm Eigenvalues are:

 [[16.+0.j]
 [18.+0.j]
 [20.+0.j]] 



In [7]:
D = np.array([[-7, -8, 1], [17, 18, -1], [-8, -8, 2]])
ShurEvalues(D)

The Original Matrix is:

 [[-7 -8  1]
 [17 18 -1]
 [-8 -8  2]] 

Upper Triangular Form of Schur Decomposition is:

 [[ 1.00000000e+01  1.55884573e+01  2.26274170e+01]
 [ 0.00000000e+00  1.00000000e+00 -5.87707683e-15]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e+00]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[-4.08248290e-01  7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01 -1.14613315e-15  5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [10.  1.  2.] 

The Shifted QR Algorithm Eigenvalues are:

 [[10.+0.j]
 [ 1.+0.j]
 [ 2.+0.j]] 



# 12.2.2

In [8]:
E = np.array([[-1, 1, 3], [3, 3, -2], [-5, 2, 7]])
ShurEvalues(E)

The Original Matrix is:

 [[-1  1  3]
 [ 3  3 -2]
 [-5  2  7]] 

Upper Triangular Form of Schur Decomposition is:

 [[ 3.00001088e+00  5.71538135e+00 -6.98304696e+00]
 [-6.20822803e-11  3.00001088e+00  1.60358074e+00]
 [ 0.00000000e+00  0.00000000e+00  2.99997825e+00]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 0.53452207 -0.21820783  0.81649954]
 [-0.26725958  0.87287761  0.40823645]
 [ 0.80178456  0.43642872 -0.40825421]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [3.00001088 3.00001088 2.99997825] 

The Shifted QR Algorithm Eigenvalues are:

 [[2.99997556+0.00000000e+00j]
 [3.00001222-1.56707604e-05j]
 [3.00001222+1.56707604e-05j]] 



In [9]:
F = np.array([[7, -33, -15], [2, 26, 7], [-4, -50, -13]])
ShurEvalues(F)

The Original Matrix is:

 [[  7 -33 -15]
 [  2  26   7]
 [ -4 -50 -13]] 

Upper Triangular Form of Schur Decomposition is:

 [[ 10.           5.81377674 -66.82215202]
 [  0.           9.           9.79795897]
 [  0.           0.           1.        ]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 4.08248290e-01 -9.12870929e-01 -6.02477509e-17]
 [-4.08248290e-01 -1.82574186e-01  8.94427191e-01]
 [ 8.16496581e-01  3.65148372e-01  4.47213595e-01]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [10.  9.  1.] 

The Shifted QR Algorithm Eigenvalues are:

 [[10.+0.j]
 [ 9.+0.j]
 [ 1.+0.j]] 



In [10]:
G = np.array([[8, 0, 5], [-5, 3, -5], [10, 0, 13]])
ShurEvalues(G)

The Original Matrix is:

 [[ 8  0  5]
 [-5  3 -5]
 [10  0 13]] 

Upper Triangular Form of Schur Decomposition is:

 [[ 3.          0.          7.07106781]
 [ 0.          3.         -5.        ]
 [ 0.          0.         18.        ]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 0.         -0.70710678 -0.70710678]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [ 3.  3. 18.] 

The Shifted QR Algorithm Eigenvalues are:

 [[ 3.+0.j]
 [ 3.+0.j]
 [18.+0.j]] 



In [11]:
H = np.array([[-3, -1, 1], [5, 3, -1], [-2, 2, 0]])
ShurEvalues(H)

The Original Matrix is:

 [[-3 -1  1]
 [ 5  3 -1]
 [-2  2  0]] 

Upper Triangular Form of Schur Decomposition is:

 [[-1.          3.34606521 -2.75820506]
 [-0.89657547 -1.          5.328443  ]
 [ 0.          0.          2.        ]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 3.25057584e-01 -6.27963030e-01  7.07106781e-01]
 [-3.25057584e-01  6.27963030e-01  7.07106781e-01]
 [ 8.88073834e-01  4.59700843e-01  8.01919170e-17]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [-1. -1.  2.] 

The Shifted QR Algorithm Eigenvalues are:

 [[ 2.+0.j        ]
 [-1.-1.73205081j]
 [-1.+1.73205081j]] 



# 12.2.5

In [12]:
I = np.array([[4, 3, 1], [-5, -3, 0], [3, 2, 1]])
ShurEvalues(I)

The Original Matrix is:

 [[ 4  3  1]
 [-5 -3  0]
 [ 3  2  1]] 

Upper Triangular Form of Schur Decomposition is:

 [[ 3.40005801e-16 -4.39106708e+00 -7.11790997e+00]
 [ 2.27735077e-01  3.40005801e-16 -4.49930259e-02]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e+00]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[-0.49079864  0.65252078  0.57735027]
 [ 0.81049889  0.0987837   0.57735027]
 [-0.31970025 -0.75130448  0.57735027]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [3.40005801e-16 3.40005801e-16 2.00000000e+00] 

The Shifted QR Algorithm Eigenvalues are:

 [[8.8817842e-15-1.j]
 [8.8817842e-15+1.j]
 [2.0000000e+00+0.j]] 



In [13]:
J = np.array([[3, 2, 0], [-4, -2, 1], [2, 1, 0]])
ShurEvalues(J)

The Original Matrix is:

 [[ 3  2  0]
 [-4 -2  1]
 [ 2  1  0]] 

Upper Triangular Form of Schur Decomposition is:

 [[-5.16947596e-16 -4.39106708e+00  4.31025946e+00]
 [ 2.27735077e-01 -5.16947596e-16 -2.97203740e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 0.49079864 -0.65252078  0.57735027]
 [-0.81049889 -0.0987837   0.57735027]
 [ 0.31970025  0.75130448  0.57735027]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [-5.16947596e-16 -5.16947596e-16  1.00000000e+00] 

The Shifted QR Algorithm Eigenvalues are:

 [[-3.71924713e-15-1.j]
 [-3.71924713e-15+1.j]
 [ 1.00000000e+00+0.j]] 



In [14]:
K = np.array([[7, 2, -4], [-8, 0, 7], [2, -1, -2]])
ShurEvalues(K)

The Original Matrix is:

 [[ 7  2 -4]
 [-8  0  7]
 [ 2 -1 -2]] 

Upper Triangular Form of Schur Decomposition is:

 [[  2.         -13.17320123   1.70017635]
 [  0.68320523   2.          -2.26039828]
 [  0.           0.           1.        ]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 0.49079864 -0.65252078  0.57735027]
 [-0.81049889 -0.0987837   0.57735027]
 [ 0.31970025  0.75130448  0.57735027]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [2. 2. 1.] 

The Shifted QR Algorithm Eigenvalues are:

 [[2.-3.j]
 [2.+3.j]
 [1.+0.j]] 



In [15]:
L = np.array([[11, 4, -2], [-10, 0, 5], [4, 1, 2]])
ShurEvalues(L)

The Original Matrix is:

 [[ 11   4  -2]
 [-10   0   5]
 [  4   1   2]] 

Upper Triangular Form of Schur Decomposition is:

 [[  4.         -13.17320123   7.31547736]
 [  0.68320523   4.          -1.57600475]
 [  0.           0.           5.        ]] 

The Unitary Matrix Form of Schur Decomposition is:

 [[ 0.49079864 -0.65252078  0.57735027]
 [-0.81049889 -0.0987837   0.57735027]
 [ 0.31970025  0.75130448  0.57735027]] 

The Python Numpy Schur Decomposition Eigenvalues are:

 [4. 4. 5.] 

The Shifted QR Algorithm Eigenvalues are:

 [[4.-3.j]
 [4.+3.j]
 [5.+0.j]] 

